import os
import sys
import re
import pandas as pd

from snakemake.utils import min_version
from snakemake.utils import validate

from workflow_utils import normalize_config, prepare_workflow_inputs

min_version("7.0.0")

configfile: "config/analysis.yaml"

config = normalize_config(config)
validate(config, schema="config/schema/config.schema.yaml")

if config["single_paired_end"] not in ["single", "paired"]:
    print("config['single_paired_end'] must be 'single' or 'paired'!")
    sys.exit()

workflow_inputs = prepare_workflow_inputs(config, workflow_dir=".")
origin_fastq = workflow_inputs["origin_fastq"]
samples_r = workflow_inputs["samples_r"]


def build_track_base_url(config):
    parts = [config["bigDataUrl"].rstrip("/")]
    for key in ["public_output_dir", "tag_public_output_dir"]:
        value = str(config.get(key, "")).strip().strip("/")
        if value:
            parts.append(value)
    return "/".join(parts)


track_base_url = build_track_base_url(config)

analysis_samples = list(samples_r)
raw_read_samples = list(origin_fastq)


def moved_fastq_targets():
    return [
        os.path.join(config["analysis_name"] + os.sep + config["reads"], f"{sample}.fastq.gz")
        for sample in raw_read_samples
    ]


def trimming_qc_targets():
    return [
        os.path.join(config["analysis_name"] + os.sep + config["trimming_qc"], f"{sample}_qc.txt")
        for sample in analysis_samples
    ]


def bowtie2_targets():
    return [
        os.path.join(config["analysis_name"] + os.sep + config["bowtie2"], f"{sample}.bam")
        for sample in analysis_samples
    ]


def sorted_bam_targets():
    return [
        os.path.join(config["analysis_name"] + os.sep + config["sorted"], f"{sample}_sorted.bam")
        for sample in analysis_samples
    ]


def duplicate_bam_targets():
    return [
        os.path.join(config["analysis_name"] + os.sep + config["duplicates"], f"{sample}_sorted_dedup.bam")
        for sample in analysis_samples
    ]


def split_genome_targets():
    return [
        os.path.join(config["analysis_name"] + os.sep + config["splitgenome"], f"{sample}_sorted_dedup.bam")
        for sample in analysis_samples
    ]


def read_count_targets():
    return [
        os.path.join(config["analysis_name"] + os.sep + config["readcounts"], f"{sample}_readCounts.txt")
        for sample in analysis_samples
    ]


def downsampling_log_targets():
    return [
        os.path.join(config["analysis_name"] + os.sep + config["downsampling_log"], f"{sample}_sorted_dedup_downsampled.txt")
        for sample in analysis_samples
    ]


def bam_coverage_log_targets():
    return [
        os.path.join(config["analysis_name"] + os.sep + config["bam_coverage_log"], f"{sample}_downsampled.txt")
        for sample in analysis_samples
    ]


def peak_log_targets():
    return [
        os.path.join(config["analysis_name"] + os.sep + config["peaks_log"], f"{sample}_downsampled.txt")
        for sample in analysis_samples
    ]


def read_qc_targets():
    return [
        os.path.join(config["analysis_name"] + os.sep + config["reads_qc"], f"{sample}.html")
        for sample in raw_read_samples
    ]


def bowtie2_multiqc_targets():
    return [
        os.path.join(config["analysis_name"] + os.sep + config["bowtie2_qc"], f"{sample}_multiqc.html")
        for sample in analysis_samples
    ]


def duplicates_multiqc_targets():
    return [
        os.path.join(config["analysis_name"] + os.sep + config["duplicates_qc"], f"{sample}_sorted_dedup_multiqc.html")
        for sample in analysis_samples
    ]


def bam_coverage_bw_targets():
    genomes = [config["genome"], config["spikein"]]
    return [
        os.path.join(config["analysis_name"] + os.sep + config["bam_coverage"], f"{sample}_sorted_dedup_downsampled_{genome}.bw")
        for sample in analysis_samples
        for genome in genomes
    ]


include: "rules/01_upstream.smk"
include: "rules/02_qc.smk"
include: "rules/03_trackDb.smk"
include: "rules/04_folders.smk"

rule all:
    input:
        moved_fastq_targets(),
        trimming_qc_targets(),
        bowtie2_targets(),
        sorted_bam_targets(),
        duplicate_bam_targets(),
        split_genome_targets(),
        read_count_targets(),
        os.path.join(config["analysis_name"] + os.sep + config["downsampling_factor_log"], "downsamplingCalculations.txt"),
        downsampling_log_targets(),
        bam_coverage_log_targets(),
        peak_log_targets(),
        read_qc_targets(),
        bowtie2_multiqc_targets(),
        duplicates_multiqc_targets(),
        os.path.join(config["analysis_name"] + os.sep + config["track"], "trackDb.txt"),
        os.path.join(config["analysis_name"] + os.sep + config["cleaning"], "moving.txt")
